# Generated by Django 2.2.19 on 2021-02-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210224_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='type_customer',
            new_name='customer_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='type_order',
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('CEDIS', 'CEDIS'), ('SUCURSAL', 'SUCURSAL'), ('EMPRESA', 'EMPRESA')], default='CEDIS', max_length=10),
        ),
    ]
