# Generated by Django 2.2.19 on 2021-02-27 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210226_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_details',
            field=models.ManyToManyField(through='app.OrderDetail', to='app.Article'),
        ),
    ]
