# Generated by Django 2.2.19 on 2021-02-27 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210226_1814'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ErrorFields',
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_to_order', to='app.Article'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_to_article', to='app.Order'),
        ),
    ]
